env: "dev"

server:
  addr: "localhost"
  port: "8080"
  read_timeout: "10s"
  write_timeout: "10s"

sensors:
  handshake_timeout: "10s"
  entities:
    - uuid: "4bf1577c-eeda-4c5b-bcd0-fcc01f25f1fe"
      token: "74QMBHLhnqcB1Q3oYcd8Ns60tvEjoePqT7G44kpSQ8XV9w3XiW6O0nc8yYPAxwe5"
    - uuid: "bf50b26c-33e0-41a8-a8e9-69922c9e3496"
      token: "GdX7DHeLf2S6hTRrBo5k8xVNV2FFrtqfBnO319MOkspvDxVDmnDXGKWZT3upR4NW"
    - uuid: "0ca9ac23-912a-4900-881a-1bda8aa304a5"
      token: "vpJ5HQc6THBZKwVZpAS9cjegZDnVz2HwAOtLX7YMGRqYYX61SleAmVh9xs9ful3Q"

db:
  driver: "sqlite"
  dsn: "./data.db"
